// <auto-generated />
namespace AppATLComplementa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CrearClientesyClientesPersonas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CrearClientesyClientesPersonas));
        
        string IMigrationMetadata.Id
        {
            get { return "202002182224145_CrearClientesyClientesPersonas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
